using Microsoft.Win32;
using System;
using System.Collections.Generic;
using System.IO;

namespace PASPAS
{
    public static class Language
    {
        public static string Current { get; set; } = "en";

        private static readonly Dictionary<string, Dictionary<string, string>> Translations = new(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["Menu_Home"] = "Home",
                ["Menu_Options"] = "Settings",
                ["Menu_Tweaks"] = "System",
                ["Menu_Registry"] = "Registry",
                ["Menu_Uninstall"] = "Programs",
                ["Menu_About"] = "About",

                ["Registry_Disclaimer"] = "Modifying the registry may affect system stability. Deleted items cannot be restored. Proceed with caution.",
                ["Button_ScanSelected"] = "Scan Selected",
                ["Button_ScanAll"] = "Scan All",
                ["Button_Delete"] = "Delete Selected",
                ["Button_SelectAll"] = "Select All",
                ["Button_Run"] = "Run",
                ["Button_Analyze"] = "Analyze",
                ["Button_Finish"] = "Finish",
                ["Button_Stop"] = "STOP",
                ["Button_Apply"] = "Apply",
                ["Button_Refresh"] = "Refresh",
                ["Button_Uninstall"] = "Uninstall",
                ["Button_DarkMode"] = "Dark Mode",
                ["Button_LightMode"] = "Light Mode",
                ["Button_Reset"] = "Reset",

                ["Status_Ready"] = "Ready",
                ["Status_Cleaning"] = "Cleaning...",
                ["Status_Analyzing"] = "Analyzing...",
                ["Status_Completed"] = "Completed",
                ["Status_Stopped"] = "Stopped",
                ["Status_Loading"] = "Loading...",
                ["Label_StatsSubtext"] = "Item / Rejected / Error",

                ["Tweaks_Disclaimer"] = "You are responsible for any damage/malfunction that may occur to your device.",
                ["Programs_Risk"] = "You are responsible for any uninstalled software. Ensure you do not uninstall critical system drivers.",

                ["About_EcoTitle"] = "Berkay Gediz's Ecosystem",
                ["About_EcoSub"] = "A truly transparent, fully open-source ecosystem.",

                ["Home_Basic_Title"] = "Basic",
                ["Home_Basic_Desc"] = "Clears clipboard, temporary files, downloaded installations, recents, preview cache, DNS cache, and system logs.",
                ["Home_Advanced_Title"] = "Advanced",
                ["Home_Advanced_Desc"] = "Includes Basic. Adds system cache, memory dumps (crash/minidumps), prefetch data, font cache, and download cache.",
                ["Home_Custom_Title"] = "Custom",
                ["Home_Custom_Desc"] = "Includes Advanced. Adds old Windows installations, error reports, and detailed system logs. Configure in Options.",

                ["Options_Clipboard_Title"] = "Clear Clipboard",
                ["Options_Clipboard_Desc"] = "Empties the current system clipboard content to prevent sensitive data leaks.",
                ["Options_TempFiles_Title"] = "Temporary Files",
                ["Options_TempFiles_Desc"] = "Deletes temporary files created by Windows and third-party applications in user and system directories.",
                ["Options_DownloadedInst_Title"] = "Downloaded Installations",
                ["Options_DownloadedInst_Desc"] = "Removes cached installation packages from the user profile, freeing up disk space.",
                ["Options_Recent_Title"] = "Recently Used Files",
                ["Options_Recent_Desc"] = "Clears Jump Lists and recent document history from the Start menu and taskbar.",
                ["Options_Preview_Title"] = "Preview Cache",
                ["Options_Preview_Desc"] = "Resets thumbnail and icon caches, fixing incorrect file previews in File Explorer.",
                ["Options_DNS_Title"] = "Flush DNS Cache",
                ["Options_DNS_Desc"] = "Flushes the DNS resolver cache to resolve network connectivity and website loading issues.",
                ["Options_Logs_Title"] = "System Logs",
                ["Options_Logs_Desc"] = "Deletes Windows Update logs and WMI activity logs to free up minor disk space.",
                ["Options_SysCache_Title"] = "System Cache",
                ["Options_SysCache_Desc"] = "Clears Windows Explorer and Token Broker caches to refresh system UI elements and tokens.",
                ["Options_MemDumps_Title"] = "Memory Dumps",
                ["Options_MemDumps_Desc"] = "Removes crash dump files (minidumps and live kernel dumps) generated by system failures.",
                ["Options_Prefetch_Title"] = "Prefetch Data",
                ["Options_Prefetch_Desc"] = "Clears Prefetch data. Windows will rebuild this over time to optimize app launch speeds.",
                ["Options_FontCache_Title"] = "Font Cache",
                ["Options_FontCache_Desc"] = "Resets the Windows Font Cache to resolve issues with corrupted or missing font rendering.",
                ["Options_DownCache_Title"] = "Windows Update Cache",
                ["Options_DownCache_Desc"] = "Deletes cached Windows Update downloads, forcing a fresh download if updates are pending.",
                ["Options_OldWin_Title"] = "Old Windows Installation",
                ["Options_OldWin_Desc"] = "Removes the $Windows.~BT or Windows.old folder. This action is irreversible and prevents rollback.",
                ["Options_SysLogErr_Title"] = "Error Reports & ETL Logs",
                ["Options_SysLogErr_Desc"] = "Deletes Windows Error Reporting (WER) queues, Cryptnet URL caches, and diagnostic ETL logs.",

                ["Tweaks_Services_Title"] = "Set Services to Manual",
                ["Tweaks_Services_Desc"] = "Configures unnecessary background services to run manually, saving system resources.",
                ["Tweaks_Telemetry_Title"] = "Disable Telemetry",
                ["Tweaks_Telemetry_Desc"] = "Disables Windows telemetry, tracking, and data collection scripts permanently.",
                ["Tweaks_Activity_Title"] = "Disable Activity History",
                ["Tweaks_Activity_Desc"] = "Prevents Windows from recording and syncing user activity history across devices.",

                ["Msg_ServicesSuccess"] = "Services set to manual successfully.",
                ["Msg_ServicesFail"] = "Failed to set services.",
                ["Msg_TelemetrySuccess"] = "Telemetry disabled successfully.",
                ["Msg_TelemetryFail"] = "Failed to disable telemetry.",
                ["Msg_ActivitySuccess"] = "Activity history disabled successfully.",
                ["Msg_ActivityFail"] = "Failed to disable activity history."
            },
            ["tr"] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["Menu_Home"] = "Ana Sayfa",
                ["Menu_Options"] = "Ayarlar",
                ["Menu_Tweaks"] = "Sistem",
                ["Menu_Registry"] = "Kayıt Defteri",
                ["Menu_Uninstall"] = "Programlar",
                ["Menu_About"] = "Hakkında",

                ["Registry_Disclaimer"] = "Kayıt defterinde değişiklik yapmak sistem kararlılığını etkileyebilir. Silinen öğeler geri alınamaz. Lütfen dikkatli olun.",
                ["Button_ScanSelected"] = "Seçilenleri Tara",
                ["Button_ScanAll"] = "Tümünü Tara",
                ["Button_Delete"] = "Seçilenleri Sil",
                ["Button_SelectAll"] = "Tümünü Seç",
                ["Button_Run"] = "Çalıştır",
                ["Button_Analyze"] = "Analiz Et",
                ["Button_Finish"] = "Bitir",
                ["Button_Stop"] = "DURDUR",
                ["Button_Apply"] = "Uygula",
                ["Button_Refresh"] = "Yenile",
                ["Button_Uninstall"] = "Kaldır",
                ["Button_DarkMode"] = "Karanlık Mod",
                ["Button_LightMode"] = "Aydınlık Mod",
                ["Button_Reset"] = "Sıfırla",

                ["Status_Ready"] = "Hazır",
                ["Status_Cleaning"] = "Temizleniyor...",
                ["Status_Analyzing"] = "Analiz Ediliyor...",
                ["Status_Completed"] = "Tamamlandı",
                ["Status_Stopped"] = "Durduruldu",
                ["Status_Loading"] = "Yükleniyor...",
                ["Label_StatsSubtext"] = "Öğe / Reddedilen / Hata",

                ["Tweaks_Disclaimer"] = "Cihazınızda oluşabilecek herhangi bir hasar/arızadan siz sorumlusunuz.",
                ["Programs_Risk"] = "Kaldırılan yazılımlardan siz sorumlusunuz. Kritik sistem sürücülerini kaldırmadığınızdan emin olun.",

                ["About_EcoTitle"] = "Berkay Gediz'in Ekosistemi",
                ["About_EcoSub"] = "Tamamen şeffaf, tamamen açık kaynak bir ekosistem.",

                ["Home_Basic_Title"] = "Temel",
                ["Home_Basic_Desc"] = "Pano, geçici dosyalar, indirilen kurulumlar, son kullanılanlar, önizleme önbelleği, DNS önbelleği ve sistem günlüklerini temizler.",
                ["Home_Advanced_Title"] = "Gelişmiş",
                ["Home_Advanced_Desc"] = "Temel'i kapsar. Sistem önbelleği, bellek dökümleri, prefetch verileri, yazı tipi önbelleği ve indirme önbelleği ekler.",
                ["Home_Custom_Title"] = "Özel",
                ["Home_Custom_Desc"] = "Gelişmiş'i kapsar. Eski Windows kurulumları, hata raporları ve ayrıntılı sistem günlükleri ekler.",

                ["Options_Clipboard_Title"] = "Panoyu Temizle",
                ["Options_Clipboard_Desc"] = "Hassas veri sızıntılarını önlemek için geçerli sistem panosu içeriğini boşaltır.",
                ["Options_TempFiles_Title"] = "Geçici Dosyalar",
                ["Options_TempFiles_Desc"] = "Windows ve üçüncü taraf uygulamaların oluşturduğu geçici dosyaları siler.",
                ["Options_DownloadedInst_Title"] = "İndirilen Kurulumlar",
                ["Options_DownloadedInst_Desc"] = "Önbelleğe alınmış kurulum paketlerini kaldırarak disk alanı açar.",
                ["Options_Recent_Title"] = "Son Kullanılan Dosyalar",
                ["Options_Recent_Desc"] = "Başlat menüsü ve görev çubuğundaki son belge geçmişini temizler.",
                ["Options_Preview_Title"] = "Önizleme Önbelleği",
                ["Options_Preview_Desc"] = "Küçük resim ve simge önbelleklerini sıfırlayarak yanlış önizlemeleri düzeltir.",
                ["Options_DNS_Title"] = "DNS Önbelleğini Temizle",
                ["Options_DNS_Desc"] = "Ağ bağlantısı ve web sitesi yükleme sorunlarını çözmek için DNS önbelleğini temizler.",
                ["Options_Logs_Title"] = "Sistem Günlükleri",
                ["Options_Logs_Desc"] = "Windows Update ve WMI etkinlik günlüklerini silerek disk alanı açar.",
                ["Options_SysCache_Title"] = "Sistem Önbelleği",
                ["Options_SysCache_Desc"] = "Windows Gezgini ve Token Broker önbelleklerini temizleyerek arayüzü yeniler.",
                ["Options_MemDumps_Title"] = "Bellek Dökümleri",
                ["Options_MemDumps_Desc"] = "Sistem arızalarının oluşturduğu çökme dökümü dosyalarını kaldırır.",
                ["Options_Prefetch_Title"] = "Prefetch Verileri",
                ["Options_Prefetch_Desc"] = "Prefetch verilerini temizler. Windows bunu uygulama hızını artırmak için zamanla yeniden oluşturur.",
                ["Options_FontCache_Title"] = "Yazı Tipi Önbelleği",
                ["Options_FontCache_Desc"] = "Bozuk veya eksik yazı tipi sorunlarını çözmek için Windows Yazı Tipi Önbelleğini sıfırlar.",
                ["Options_DownCache_Title"] = "Windows Update Önbelleği",
                ["Options_DownCache_Desc"] = "Bekleyen güncellemeler varsa yeni indirmeye zorlayarak önbelleği siler.",
                ["Options_OldWin_Title"] = "Eski Windows Kurulumu",
                ["Options_OldWin_Desc"] = "$Windows.~BT veya Windows.old klasörünü kaldırır. Bu işlem geri alınamaz.",
                ["Options_SysLogErr_Title"] = "Hata Raporları ve ETL Günlükleri",
                ["Options_SysLogErr_Desc"] = "Windows Hata Bildirim kuyruklarını ve tanılama ETL günlüklerini siler.",

                ["Tweaks_Services_Title"] = "Hizmetleri Manuel Olarak Ayarla",
                ["Tweaks_Services_Desc"] = "Gereksiz arka plan hizmetlerini manuel çalıştırarak sistem kaynaklarını korur.",
                ["Tweaks_Telemetry_Title"] = "Telemetriyi Devre Dışı Bırak",
                ["Tweaks_Telemetry_Desc"] = "Windows telemetri ve veri toplama betiklerini kalıcı olarak devre dışı bırakır.",
                ["Tweaks_Activity_Title"] = "Etkinlik Geçmişini Devre Dışı Bırak",
                ["Tweaks_Activity_Desc"] = "Cihazlar arası kullanıcı etkinlik geçmişinin kaydedilip senkronize edilmesini engeller.",

                ["Msg_ServicesSuccess"] = "Hizmetler manuel olarak ayarlandı.",
                ["Msg_ServicesFail"] = "Hizmetler ayarlanamadı.",
                ["Msg_TelemetrySuccess"] = "Telemetri devre dışı bırakıldı.",
                ["Msg_TelemetryFail"] = "Telemetri devre dışı bırakılamadı.",
                ["Msg_ActivitySuccess"] = "Etkinlik geçmişi devre dışı bırakıldı.",
                ["Msg_ActivityFail"] = "Etkinlik geçmişi devre dışı bırakılamadı."
            }
        };

        public static string Get(string key)
        {
            if (Translations.TryGetValue(Current, out var lang) && lang.TryGetValue(key, out var val))
                return val;
            return key;
        }
    }

    public static class Globals
    {
        public static readonly string SystemDirectory = Path.GetPathRoot(Environment.SystemDirectory);

        public static readonly Dictionary<string, string> FolderIndex = new()
        {
            { "WinTemp", "Windows\\TEMP" },
            { "WinTemp2", "Users\\" + Environment.UserName + "\\AppData\\Local\\Temp" },
            { "DownloadedInstallations", "Users\\" + Environment.UserName + "\\AppData\\Roaming\\Downloaded Installations" },
            { "CryptnetUrlCacheContent", "Windows\\System32\\config\\systemprofile\\AppData\\LocalLow\\Microsoft\\CryptnetUrlCache\\Content"},
            { "CryptnetUrlCacheMetaData", "Windows\\System32\\config\\systemprofile\\AppData\\LocalLow\\Microsoft\\CryptnetUrlCache\\MetaData"},
            { "NetworkServiceTemp", "Windows\\ServiceProfiles\\NetworkService\\AppData\\Local\\Temp"},
            { "TokenBrokerCache", "Users\\" + Environment.UserName + "\\AppData\\Local\\Microsoft\\TokenBroker\\Cache"},
            { "waasmedicLog", "Windows\\Logs\\waasmedic"},
            { "NetSetupLog", "Windows\\Logs\\NetSetup"},
            { "ReportArchive", "ProgramData\\Microsoft\\Windows\\WER\\ReportArchive"},
            { "ReportQueue", "ProgramData\\Microsoft\\Windows\\WER\\ReportQueue"},
            { "WERTemp", "ProgramData\\Microsoft\\Windows\\WER\\Temp"},
            { "RecentFiles", "Users\\" + Environment.UserName + "\\AppData\\Roaming\\Microsoft\\Windows\\Recent" },
            { "RecentFiles2", "Users\\" + Environment.UserName + "\\AppData\\Roaming\\Microsoft\\Windows\\Recent\\AutomaticDestinations" },
            { "RecentFiles3", "Users\\" + Environment.UserName + "\\AppData\\Roaming\\Microsoft\\Windows\\Recent\\CustomDestinations" },
            { "PreviewCache", "Users\\" + Environment.UserName + "\\AppData\\Local\\Microsoft\\Windows\\Explorer" },
            { "Logs", "Windows\\SoftwareDistribution\\DataStore\\Logs" },
            { "Logs2", "Windows\\System32\\wbem\\Logs" },
            { "UpdateReport", "Windows\\SoftwareDistribution\\" },
            { "SystemCache", "Users\\" + Environment.UserName + "\\AppData\\Local\\Microsoft\\Windows\\Explorer" },
            { "LiveKernelReports", "Windows\\LiveKernelReports" },
            { "LiveKernelNDIS", "Windows\\LiveKernelReports\\NDIS" },
            { "CrashDumps", "Users\\" + Environment.UserName + "\\AppData\\Local\\CrashDumps" },
            { "MiniDumps", "Windows\\Minidump" },
            { "Prefetch", "Windows\\Prefetch" },
            { "DownloadCache", "Windows\\SoftwareDistribution\\Download" },
            { "FontCache", "Windows\\System32" },
            { "OldWindows", "$Windows.old" }
        };

        public static readonly string[] TemporaryExtensions = [".tmp", ".log", ".txt", ".dat", ".iss", ".exe", ".ini", ".vbs", ".cvr", ".od", ".lnk", ".js", ".5f2", ".jro", ".41u", ".w0y", ".vmo", ".diagsession", ".png", ".jpg", ".jpeg", ".q13", ".2im", ".html", ".rcl", ".5ar", ".xml", ".dll", ".Mtx"];

        public static readonly Dictionary<string, string> ServiceConfigurations = new()
        {
            { "InstallService", "Manual" }, { "InventorySvc", "Manual" }, { "IpxlatCfgSvc", "Manual" },
            { "KeyIso", "Automatic" }, { "KtmRm", "Manual" }, { "LSM", "Automatic" },
            { "LanmanServer", "Automatic" }, { "LanmanWorkstation", "Automatic" }, { "LicenseManager", "Manual" },
            { "LxpSvc", "Manual" }, { "MSDTC", "Manual" }, { "MSiSCSI", "Manual" },
            { "MapsBroker", "AutomaticDelayedStart" }, { "McpManagementService", "Manual" }, { "MessagingService_*", "Manual" },
            { "MicrosoftEdgeElevationService", "Manual" }, { "MixedRealityOpenXRSvc", "Manual" }, { "MpsSvc", "Automatic" },
            { "MsKeyboardFilter", "Manual" }, { "NPSMSvc_*", "Manual" }, { "NaturalAuthentication", "Manual" },
            { "NcaSvc", "Manual" }, { "NcbService", "Manual" }, { "NcdAutoSetup", "Manual" },
            { "NetSetupSvc", "Manual" }, { "NetTcpPortSharing", "Disabled" }, { "Netlogon", "Automatic" },
            { "Netman", "Manual" }, { "NgcCtnrSvc", "Manual" }, { "NgcSvc", "Manual" },
            { "NlaSvc", "Manual" }, { "OneSyncSvc_*", "Automatic" }, { "P9RdrService_*", "Manual" },
            { "PNRPAutoReg", "Manual" }, { "PNRPsvc", "Manual" }, { "PcaSvc", "Manual" },
            { "PeerDistSvc", "Manual" }, { "PenService_*", "Manual" }, { "PerfHost", "Manual" },
            { "PhoneSvc", "Manual" }, { "PimIndexMaintenanceSvc_*", "Manual" }, { "PlugPlay", "Manual" },
            { "PolicyAgent", "Manual" }, { "Power", "Automatic" }, { "PrintNotify", "Manual" },
            { "PrintWorkflowUserSvc_*", "Manual" }, { "ProfSvc", "Automatic" }, { "PushToInstall", "Manual" },
            { "QWAVE", "Manual" }, { "RasAuto", "Manual" }, { "RasMan", "Manual" },
            { "RemoteAccess", "Disabled" }, { "RemoteRegistry", "Disabled" }, { "RetailDemo", "Manual" },
            { "RmSvc", "Manual" }, { "RpcEptMapper", "Automatic" }, { "RpcLocator", "Manual" },
            { "RpcSs", "Automatic" }, { "SCPolicySvc", "Manual" }, { "SCardSvr", "Manual" },
            { "SDRSVC", "Manual" }, { "SEMgrSvc", "Manual" }, { "SENS", "Automatic" },
            { "SNMPTRAP", "Manual" }, { "SNMPTrap", "Manual" }, { "SSDPSRV", "Manual" },
            { "SamSs", "Automatic" }, { "ScDeviceEnum", "Manual" }, { "Schedule", "Automatic" },
            { "SecurityHealthService", "Manual" }, { "Sense", "Manual" }, { "SensorDataService", "Manual" },
            { "SensorService", "Manual" }, { "SensrSvc", "Manual" }, { "SessionEnv", "Manual" },
            { "SgrmBroker", "Automatic" }, { "SharedAccess", "Manual" }, { "SharedRealitySvc", "Manual" },
            { "ShellHWDetection", "Automatic" }, { "SmsRouter", "Manual" }, { "Spooler", "Automatic" },
            { "SstpSvc", "Manual" }, { "StateRepository", "Manual" }, { "StiSvc", "Manual" },
            { "StorSvc", "Manual" }, { "SysMain", "Automatic" }, { "SystemEventsBroker", "Automatic" },
            { "TabletInputService", "Manual" }, { "TapiSrv", "Manual" }, { "TermService", "Automatic" },
            { "TextInputManagementService", "Manual" }, { "Themes", "Automatic" }, { "TieringEngineService", "Manual" },
            { "TimeBroker", "Manual" }, { "TimeBrokerSvc", "Manual" }, { "TokenBroker", "Manual" },
            { "TrkWks", "Automatic" }, { "TroubleshootingSvc", "Manual" }, { "TrustedInstaller", "Manual" },
            { "UI0Detect", "Manual" }, { "UdkUserSvc_*", "Manual" }, { "UevAgentService", "Disabled" },
            { "UmRdpService", "Manual" }, { "UnistoreSvc_*", "Manual" }, { "UserDataSvc_*", "Manual" },
            { "UserManager", "Automatic" }, { "UsoSvc", "Manual" }, { "VGAuthService", "Automatic" },
            { "VMTools", "Automatic" }, { "VSS", "Manual" }, { "VacSvc", "Manual" },
            { "VaultSvc", "Automatic" }, { "W32Time", "Manual" }, { "WEPHOSTSVC", "Manual" },
            { "WFDSConMgrSvc", "Manual" }, { "WMPNetworkSvc", "Manual" }, { "WManSvc", "Manual" },
            { "WPDBusEnum", "Manual" }, { "WSService", "Manual" }, { "WSearch", "AutomaticDelayedStart" },
            { "WaaSMedicSvc", "Manual" }, { "WalletService", "Manual" }, { "WarpJITSvc", "Manual" },
            { "WbioSrvc", "Manual" }, { "Wcmsvc", "Automatic" }, { "WcsPlugInService", "Manual" },
            { "WdNisSvc", "Manual" }, { "WdiServiceHost", "Manual" }, { "WdiSystemHost", "Manual" },
            { "WebClient", "Manual" }, { "Wecsvc", "Manual" }, { "WerSvc", "Manual" },
            { "WiaRpc", "Manual" }, { "WinDefend", "Automatic" }, { "WinHttpAutoProxySvc", "Manual" },
            { "WinRM", "Manual" }, { "Winmgmt", "Automatic" }, { "WlanSvc", "Automatic" },
            { "WpcMonSvc", "Manual" }, { "WpnService", "Manual" }, { "WpnUserService_*", "Automatic" },
            { "XblAuthManager", "Manual" }, { "XblGameSave", "Manual" }, { "XboxGipSvc", "Manual" },
            { "XboxNetApiSvc", "Manual" }, { "autotimesvc", "Manual" }, { "bthserv", "Manual" },
            { "camsvc", "Manual" }, { "cbdhsvc_*", "Manual" }, { "cloudidsvc", "Manual" },
            { "dcsvc", "Manual" }, { "defragsvc", "Manual" }, { "diagnosticshub.standardcollector.service", "Manual" },
            { "diagsvc", "Manual" }, { "dmwappushservice", "Manual" }, { "dot3svc", "Manual" },
            { "edgeupdate", "Manual" }, { "edgeupdatem", "Manual" }, { "embeddedmode", "Manual" },
            { "fdPHost", "Manual" }, { "fhsvc", "Manual" }, { "gpsvc", "Automatic" },
            { "hidserv", "Manual" }, { "icssvc", "Manual" }, { "iphlpsvc", "Automatic" },
            { "lfsvc", "Manual" }, { "lltdsvc", "Manual" }, { "lmhosts", "Manual" },
            { "mpssvc", "Automatic" }, { "msiserver", "Manual" }, { "netprofm", "Manual" },
            { "nsi", "Automatic" }, { "p2pimsvc", "Manual" }, { "p2psvc", "Manual" },
            { "perceptionsimulation", "Manual" }, { "pla", "Manual" }, { "seclogon", "Manual" },
            { "shpamsvc", "Disabled" }, { "smphost", "Manual" }, { "spectrum", "Manual" },
            { "sppsvc", "AutomaticDelayedStart" }, { "ssh-agent", "Disabled" }, { "svsvc", "Manual" },
            { "swprv", "Manual" }, { "tiledatamodelsvc", "Automatic" }, { "tzautoupdate", "Disabled" },
            { "uhssvc", "Disabled" }, { "upnphost", "Manual" }, { "vds", "Manual" },
            { "vm3dservice", "Manual" }, { "vmicguestinterface", "Manual" }, { "vmicheartbeat", "Manual" },
            { "vmickvpexchange", "Manual" }, { "vmicrdv", "Manual" }, { "vmicshutdown", "Manual" },
            { "vmictimesync", "Manual" }, { "vmicvmsession", "Manual" }, { "vmicvss", "Manual" },
            { "vmvss", "Manual" }, { "wbengine", "Manual" }, { "wcncsvc", "Manual" },
            { "webthreatdefsvc", "Manual" }, { "webthreatdefusersvc_*", "Automatic" }, { "wercplsupport", "Manual" },
            { "wisvc", "Manual" }, { "wlidsvc", "Manual" }, { "wlpasvc", "Manual" },
            { "wmiApSrv", "Manual" }, { "workfolderssvc", "Manual" }, { "wscsvc", "AutomaticDelayedStart" },
            { "wuauserv", "Manual" }, { "wudfsvc", "Manual" }
        };

        public static readonly string[] SystemPaths = [@"c:\windows\", @"\windowsapps\", @"\package cache\", @"\winget\", @"\swsetup\", @"\drivers\", @"\oem\", @"\\"];
        public static readonly string[] VendorKeywords = [
            @"\intel", @"\amd", @"\qualcomm", @"\mediatek", @"\broadcom", @"\marvell", @"\via\",
            @"\nvidia corporation", @"\nvidia\", @"\realtek", @"\conexant", @"\creative", @"\dolby", @"\dts", @"\c-media",
            @"\atheros", @"\synaptics", @"\elan",
            @"\asus", @"\asustek", @"\msi\", @"\micro-star international", @"\gigabyte", @"\asrock", @"\biostar", @"\elitegroup",
            @"\hp\", @"\hewlett-packard", @"\dell", @"\lenovo", @"\acer", @"\samsung", @"\toshiba", @"\sony",
            @"\lg electronics", @"\fujitsu", @"\panasonic", @"\microsoft\"
        ];

        public static readonly Dictionary<string, string> KnownFolders = new()
        {
            { "{6D809377-6AF0-444B-8957-A3773F02200E}", @"C:\Program Files\" },
            { "{7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}", @"C:\Program Files (x86)\" },
            { "{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}", @"C:\Windows\System32\" },
            { "{F38BF404-1D43-42F2-9305-67DE0B28FC23}", @"C:\Windows\SysWOW64\" },
            { "{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}", @"C:\Windows\System32\WindowsPowerShell\v1.0\" }
        };

        public static readonly Dictionary<string, RegistryCategory> RegistryCategories = new()
        {
            ["MuiCache"] = new RegistryCategory { Title = "MuiCache", Desc = "Application Traces and Cache", Root = Registry.CurrentUser, Paths = new[] { @"Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache" }, ScanSubKeys = false, Excludes = Array.Empty<string>(), CheckFiles = true, Suffixes = new[] { ".FriendlyAppName", ".ApplicationCompany" } },
            ["FeatureUsage"] = new RegistryCategory { Title = "FeatureUsage", Desc = "Taskbar and Start Menu Counters", Root = Registry.CurrentUser, Paths = new[] { @"Software\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\AppBadgeUpdated", @"Software\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\AppLaunch", @"Software\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\AppSwitched", @"Software\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\ShowJumpView" }, ScanSubKeys = false, Excludes = Array.Empty<string>(), CheckFiles = true, CheckPids = true },
            ["TileProperties"] = new RegistryCategory { Title = "TileProperties", Desc = "Start Menu Tiles", Root = Registry.CurrentUser, Paths = new[] { @"Software\Microsoft\Windows\CurrentVersion\Start\TileProperties" }, ScanSubKeys = true, Excludes = new[] { "P~", "W~{", "W~http", "W~C:", "W~D:", "W~E:", "W~Microsoft.", "W~MSEdge", "W~Windows.", "W~Brave", "W~VisualStudio.", "W~TheDocumentFoundation.LibreOffice.", "W~com.nvidia.nvapp", "W~Intel.", "W~Blend.", "W~308046B0AF4A39CB", "W~CA9422711AE1A81C", "W~F0DC299D809B9700", "W~PrivateBrowsingAUMID" }, UnknownIsJunk = true },
            ["AppAssociationToasts"] = new RegistryCategory { Title = "AppAssociationToasts", Desc = "File Association Notifications", Root = Registry.CurrentUser, Paths = new[] { @"Software\Microsoft\Windows\CurrentVersion\ApplicationAssociationToasts" }, ScanSubKeys = false, Excludes = new[] { "AppX", "ms-", "MSEdgeHTM", "MSEdgePDF", "MSEdgeMHT", "CompressedFolder", "ArchiveFolder", "Windows.IsoFile", "JSFile", "regfile", "ttffile", "chm.file", "CABFolder", "MSCFile", "Msi.Package", "InternetShortcut", "vcard", "wab_auto_file", "wdpfile", "TIFImage.Document", "MSInfoFile", "Undecided", "dbfile", "PSPP System File", "FirefoxURL", "FirefoxHTML", "FirefoxPDF", "ChromeHTML", "ChromePDF", "VisualStudio.", "TheDocumentFoundation.LibreOffice.", "soffice.StarCalcDocument", "soffice.StarWriterDocument" }, CheckProgIds = true },
            ["Notifications"] = new RegistryCategory { Title = "Notifications", Desc = "Notification Settings", Root = Registry.CurrentUser, Paths = new[] { @"Software\Microsoft\Windows\CurrentVersion\Notifications\Settings" }, ScanSubKeys = true, Excludes = new[] { "Windows.", "Microsoft.", "AD2F1837.", "AppUp.", "DTSInc.", "KDEe.", "NearbyShare_", "windows.immersivecontrolpanel_", "com.nvidia.nvapp", "Intel.Dsa.Tray" }, CheckFiles = true, CheckNotifyIcons = true },
            ["JumplistData"] = new RegistryCategory { Title = "JumplistData", Desc = "Search Recent Items", Root = Registry.CurrentUser, Paths = new[] { @"Software\Microsoft\Windows\CurrentVersion\Search\JumplistData" }, ScanSubKeys = false, Excludes = Array.Empty<string>(), CheckFiles = true },
            ["AppCompatFlags"] = new RegistryCategory { Title = "AppCompatFlags", Desc = "Compatibility Assistant and Leftovers", Root = Registry.CurrentUser, Paths = new[] { @"Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store", @"Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" }, ScanSubKeys = false, Excludes = Array.Empty<string>(), CheckFiles = true },
            ["CommitHistory"] = new RegistryCategory { Title = "CommitHistory", Desc = "Background Activity History", Root = Registry.CurrentUser, Paths = new[] { @"Software\Microsoft\Windows NT\CurrentVersion\HostActivityManager\CommitHistory" }, ScanSubKeys = true, Excludes = new[] { "Microsoft.", "MicrosoftWindows.", "windows.", "Windows.", "AD2F1837.", "AppUp.", "DTSInc.", "DolbyLaboratories.", "KDEe.", "NearbyShare_", "NVIDIACorp.", "PythonSoftwareFoundation.", "AmazonVideo." }, UnknownIsJunk = true },
            ["HKU_SysAccounts"] = new RegistryCategory { Title = "HKU System Accounts", Desc = "3rd Party Leftovers in System Accounts", Root = Registry.Users, Paths = new[] { ".DEFAULT\\Software", "S-1-5-18\\Software", "S-1-5-19\\Software", "S-1-5-20\\Software" }, ScanSubKeys = true, Excludes = new[] { "Microsoft", "Classes", "Policies", "Clients", "RegisteredApplications", "AppX", "WOW6432Node", "AppDataLow", "Intel", "HP", "Hewlett-Packard", "AMD", "NVIDIA Corporation", "Realtek", "Qualcomm", "Synaptics", "Dell", "Lenovo", "ASUS", "Samsung", "Toshiba" }, UnknownIsJunk = true }
        };
    }

    public class RegistryItem
    {
        public RegistryKey Root;
        public string Path;
        public string Name;
        public bool IsSubKey;
        public override string ToString() => Root == Registry.Users ? $"{Path}\\{Name}" : Name;
    }

    public class RegistryCategory
    {
        public string Title;
        public string Desc;
        public RegistryKey Root;
        public string[] Paths;
        public bool ScanSubKeys;
        public string[] Excludes;
        public bool CheckFiles, CheckPids, CheckProgIds, CheckNotifyIcons, UnknownIsJunk;
        public string[] Suffixes;
    }
}