name: Release PASPAS

on:
  push:
    tags:
      - '[0-9]+.*' # version: 2.0.1.0

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [win-x64, win-x86, win-arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        allow-prerelease: true

    - name: Publish Single File Executable
      run: dotnet publish PASPAS.csproj -c Release -r ${{ matrix.arch }} -p:PublishSingleFile=true -p:SelfContained=true -p:ReadyToRun=false -p:PublishTrimmed=false --output ./publish

    - name: Create Portable Zip
      run: Compress-Archive -Path ./publish/PASPAS.exe -DestinationPath ./PASPAS-${{ github.ref_name }}-${{ matrix.arch }}-portable.zip

    - name: Install Inno Setup
      run: choco install innosetup -y --no-progress

    - name: Create Installer (Setup.exe)
      run: iscc installer.iss /DMyArch=${{ matrix.arch }} /DMyVersion=${{ github.ref_name }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PASPAS-${{ matrix.arch }}
        path: |
          ./PASPAS-${{ github.ref_name }}-${{ matrix.arch }}-portable.zip
          ./PASPAS-${{ github.ref_name }}-Setup-${{ matrix.arch }}.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
